"""add_investigation_fields_and_indexes

Revision ID: 2458617ad8e0
Revises: c28a75e9da65
Create Date: 2026-02-19 07:07:56.003506

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2458617ad8e0'
down_revision: Union[str, None] = 'c28a75e9da65'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_bug_reports_slack_thread_ts', 'bug_reports', ['slack_thread_ts'], unique=False)
    op.add_column('investigations', sa.Column('conversation_history', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('investigations', sa.Column('summary_thread_ts', sa.String(length=30), nullable=True))
    op.create_index('idx_investigations_summary_thread_ts', 'investigations', ['summary_thread_ts'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_investigations_summary_thread_ts', table_name='investigations')
    op.drop_column('investigations', 'summary_thread_ts')
    op.drop_column('investigations', 'conversation_history')
    op.drop_index('idx_bug_reports_slack_thread_ts', table_name='bug_reports')
    # ### end Alembic commands ###
