"""add_claude_session_id_to_investigations

Revision ID: 9dfeb93f9938
Revises: 2458617ad8e0
Create Date: 2026-02-19 10:38:07.350934

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9dfeb93f9938'
down_revision: Union[str, None] = '2458617ad8e0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('investigations', sa.Column('claude_session_id', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('investigations', 'claude_session_id')
    # ### end Alembic commands ###
