"""initial tables

Revision ID: c28a75e9da65
Revises: 
Create Date: 2026-02-17 22:36:13.261107

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c28a75e9da65'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bug_reports',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('bug_id', sa.String(length=50), nullable=False),
    sa.Column('slack_channel_id', sa.String(length=20), nullable=False),
    sa.Column('slack_thread_ts', sa.String(length=30), nullable=False),
    sa.Column('reporter_user_id', sa.String(length=20), nullable=False),
    sa.Column('original_message', sa.Text(), nullable=False),
    sa.Column('severity', sa.String(length=5), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('temporal_workflow_id', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('bug_id')
    )
    op.create_index('idx_bug_reports_severity', 'bug_reports', ['severity'], unique=False)
    op.create_index('idx_bug_reports_status', 'bug_reports', ['status'], unique=False)
    op.create_table('service_team_mapping',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('service_name', sa.String(length=100), nullable=False),
    sa.Column('github_repo', sa.String(length=200), nullable=False),
    sa.Column('team_slack_group', sa.String(length=30), nullable=True),
    sa.Column('primary_oncall', sa.String(length=20), nullable=True),
    sa.Column('tech_stack', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sla_configs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('severity', sa.String(length=5), nullable=False),
    sa.Column('acknowledgement_target_min', sa.Integer(), nullable=False),
    sa.Column('resolution_target_min', sa.Integer(), nullable=False),
    sa.Column('follow_up_interval_min', sa.Integer(), nullable=False),
    sa.Column('escalation_threshold', sa.Integer(), nullable=False),
    sa.Column('escalation_contacts', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('severity')
    )
    op.create_table('escalations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('bug_id', sa.String(length=50), nullable=False),
    sa.Column('escalation_level', sa.Integer(), nullable=False),
    sa.Column('escalated_to', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['bug_id'], ['bug_reports.bug_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('investigations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('bug_id', sa.String(length=50), nullable=False),
    sa.Column('root_cause', sa.Text(), nullable=True),
    sa.Column('fix_type', sa.String(length=20), nullable=False),
    sa.Column('pr_url', sa.String(length=500), nullable=True),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('relevant_services', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('recommended_actions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('cost_usd', sa.Float(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['bug_id'], ['bug_reports.bug_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('investigations')
    op.drop_table('escalations')
    op.drop_table('sla_configs')
    op.drop_table('service_team_mapping')
    op.drop_index('idx_bug_reports_status', table_name='bug_reports')
    op.drop_index('idx_bug_reports_severity', table_name='bug_reports')
    op.drop_table('bug_reports')
    # ### end Alembic commands ###
